import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
  require('../shared/infra/mock')
}

export const metadata = {
  title: 'Code styles',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
